/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DoubleEndedQueue,
  DoubleEndedQueueInterface,
} from "../../../../openzeppelin-contracts-5.0.0/utils/structs/DoubleEndedQueue";

const _abi = [
  {
    inputs: [],
    name: "QueueEmpty",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueFull",
    type: "error",
  },
  {
    inputs: [],
    name: "QueueOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c00d02c196539cdd97aeb60dd12ae5f47138bd2529c972ad2a4a076a6c3cbf4064736f6c63430008140033";

type DoubleEndedQueueConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DoubleEndedQueueConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DoubleEndedQueue__factory extends ContractFactory {
  constructor(...args: DoubleEndedQueueConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DoubleEndedQueue & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DoubleEndedQueue__factory {
    return super.connect(runner) as DoubleEndedQueue__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DoubleEndedQueueInterface {
    return new Interface(_abi) as DoubleEndedQueueInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DoubleEndedQueue {
    return new Contract(address, _abi, runner) as unknown as DoubleEndedQueue;
  }
}
