/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProxyExposed } from "./IProxyExposed";
export type { UpgradeableBeaconMock } from "./UpgradeableBeaconMock";
export type { UpgradeableBeaconReentrantMock } from "./UpgradeableBeaconReentrantMock";
