/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressArraysMock } from "./AddressArraysMock";
export type { Bytes32ArraysMock } from "./Bytes32ArraysMock";
export type { Uint256ArraysMock } from "./Uint256ArraysMock";
