/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface Uint256ArraysMockInterface extends Interface {
  getFunction(
    nameOrSignature: "findUpperBound" | "unsafeAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "findUpperBound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unsafeAccess",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "findUpperBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsafeAccess",
    data: BytesLike
  ): Result;
}

export interface Uint256ArraysMock extends BaseContract {
  connect(runner?: ContractRunner | null): Uint256ArraysMock;
  waitForDeployment(): Promise<this>;

  interface: Uint256ArraysMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  findUpperBound: TypedContractMethod<
    [element: BigNumberish],
    [bigint],
    "view"
  >;

  unsafeAccess: TypedContractMethod<[pos: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "findUpperBound"
  ): TypedContractMethod<[element: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "unsafeAccess"
  ): TypedContractMethod<[pos: BigNumberish], [bigint], "view">;

  filters: {};
}
