/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CallReceiverMockTrustingForwarderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isTrustedForwarder"
      | "mockFunction"
      | "mockFunctionEmptyReturn"
      | "mockFunctionNonPayable"
      | "mockFunctionOutOfGas"
      | "mockFunctionRevertsNoReason"
      | "mockFunctionRevertsReason"
      | "mockFunctionThrows"
      | "mockFunctionWithArgs"
      | "mockFunctionWritesStorage"
      | "mockStaticFunction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MockFunctionCalled" | "MockFunctionCalledWithArgs"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionEmptyReturn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionNonPayable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionOutOfGas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionRevertsNoReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionRevertsReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionThrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionWithArgs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionWritesStorage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockStaticFunction",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionEmptyReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionNonPayable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionOutOfGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionRevertsNoReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionRevertsReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionThrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionWithArgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionWritesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockStaticFunction",
    data: BytesLike
  ): Result;
}

export namespace MockFunctionCalledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockFunctionCalledWithArgsEvent {
  export type InputTuple = [a: BigNumberish, b: BigNumberish];
  export type OutputTuple = [a: bigint, b: bigint];
  export interface OutputObject {
    a: bigint;
    b: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CallReceiverMockTrustingForwarder extends BaseContract {
  connect(runner?: ContractRunner | null): CallReceiverMockTrustingForwarder;
  waitForDeployment(): Promise<this>;

  interface: CallReceiverMockTrustingForwarderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  mockFunction: TypedContractMethod<[], [string], "payable">;

  mockFunctionEmptyReturn: TypedContractMethod<[], [void], "payable">;

  mockFunctionNonPayable: TypedContractMethod<[], [string], "nonpayable">;

  mockFunctionOutOfGas: TypedContractMethod<[], [void], "payable">;

  mockFunctionRevertsNoReason: TypedContractMethod<[], [void], "payable">;

  mockFunctionRevertsReason: TypedContractMethod<[], [void], "payable">;

  mockFunctionThrows: TypedContractMethod<[], [void], "payable">;

  mockFunctionWithArgs: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [string],
    "payable"
  >;

  mockFunctionWritesStorage: TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [string],
    "nonpayable"
  >;

  mockStaticFunction: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mockFunction"
  ): TypedContractMethod<[], [string], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionEmptyReturn"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionNonPayable"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "mockFunctionOutOfGas"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionRevertsNoReason"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionRevertsReason"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionThrows"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mockFunctionWithArgs"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mockFunctionWritesStorage"
  ): TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mockStaticFunction"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MockFunctionCalled"
  ): TypedContractEvent<
    MockFunctionCalledEvent.InputTuple,
    MockFunctionCalledEvent.OutputTuple,
    MockFunctionCalledEvent.OutputObject
  >;
  getEvent(
    key: "MockFunctionCalledWithArgs"
  ): TypedContractEvent<
    MockFunctionCalledWithArgsEvent.InputTuple,
    MockFunctionCalledWithArgsEvent.OutputTuple,
    MockFunctionCalledWithArgsEvent.OutputObject
  >;

  filters: {
    "MockFunctionCalled()": TypedContractEvent<
      MockFunctionCalledEvent.InputTuple,
      MockFunctionCalledEvent.OutputTuple,
      MockFunctionCalledEvent.OutputObject
    >;
    MockFunctionCalled: TypedContractEvent<
      MockFunctionCalledEvent.InputTuple,
      MockFunctionCalledEvent.OutputTuple,
      MockFunctionCalledEvent.OutputObject
    >;

    "MockFunctionCalledWithArgs(uint256,uint256)": TypedContractEvent<
      MockFunctionCalledWithArgsEvent.InputTuple,
      MockFunctionCalledWithArgsEvent.OutputTuple,
      MockFunctionCalledWithArgsEvent.OutputObject
    >;
    MockFunctionCalledWithArgs: TypedContractEvent<
      MockFunctionCalledWithArgsEvent.InputTuple,
      MockFunctionCalledWithArgsEvent.OutputTuple,
      MockFunctionCalledWithArgsEvent.OutputObject
    >;
  };
}
