/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CallReceiverMock } from "./CallReceiverMock";
export type { CallReceiverMockTrustingForwarder } from "./CallReceiverMockTrustingForwarder";
