/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc165InterfacesSupportedSol from "./ERC165InterfacesSupported.sol";
export type { erc165InterfacesSupportedSol };
import type * as erc165ReturnBombSol from "./ERC165ReturnBomb.sol";
export type { erc165ReturnBombSol };
export type { ERC165MaliciousData } from "./ERC165MaliciousData";
export type { ERC165MissingData } from "./ERC165MissingData";
