/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccessManagedTargetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authority"
      | "fnRestricted"
      | "fnUnrestricted"
      | "isConsumingScheduledOp"
      | "setAuthority"
      | "setIsConsumingScheduledOp"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorityUpdated"
      | "CalledFallback"
      | "CalledRestricted"
      | "CalledUnrestricted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fnRestricted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnUnrestricted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isConsumingScheduledOp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIsConsumingScheduledOp",
    values: [boolean, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fnRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnUnrestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConsumingScheduledOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIsConsumingScheduledOp",
    data: BytesLike
  ): Result;
}

export namespace AuthorityUpdatedEvent {
  export type InputTuple = [authority: AddressLike];
  export type OutputTuple = [authority: string];
  export interface OutputObject {
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CalledFallbackEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CalledRestrictedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CalledUnrestrictedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccessManagedTarget extends BaseContract {
  connect(runner?: ContractRunner | null): AccessManagedTarget;
  waitForDeployment(): Promise<this>;

  interface: AccessManagedTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authority: TypedContractMethod<[], [string], "view">;

  fnRestricted: TypedContractMethod<[], [void], "nonpayable">;

  fnUnrestricted: TypedContractMethod<[], [void], "nonpayable">;

  isConsumingScheduledOp: TypedContractMethod<[], [string], "view">;

  setAuthority: TypedContractMethod<
    [newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  setIsConsumingScheduledOp: TypedContractMethod<
    [isConsuming: boolean, slot: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fnRestricted"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fnUnrestricted"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isConsumingScheduledOp"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthority"
  ): TypedContractMethod<[newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIsConsumingScheduledOp"
  ): TypedContractMethod<
    [isConsuming: boolean, slot: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorityUpdated"
  ): TypedContractEvent<
    AuthorityUpdatedEvent.InputTuple,
    AuthorityUpdatedEvent.OutputTuple,
    AuthorityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CalledFallback"
  ): TypedContractEvent<
    CalledFallbackEvent.InputTuple,
    CalledFallbackEvent.OutputTuple,
    CalledFallbackEvent.OutputObject
  >;
  getEvent(
    key: "CalledRestricted"
  ): TypedContractEvent<
    CalledRestrictedEvent.InputTuple,
    CalledRestrictedEvent.OutputTuple,
    CalledRestrictedEvent.OutputObject
  >;
  getEvent(
    key: "CalledUnrestricted"
  ): TypedContractEvent<
    CalledUnrestrictedEvent.InputTuple,
    CalledUnrestrictedEvent.OutputTuple,
    CalledUnrestrictedEvent.OutputObject
  >;

  filters: {
    "AuthorityUpdated(address)": TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;
    AuthorityUpdated: TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;

    "CalledFallback(address)": TypedContractEvent<
      CalledFallbackEvent.InputTuple,
      CalledFallbackEvent.OutputTuple,
      CalledFallbackEvent.OutputObject
    >;
    CalledFallback: TypedContractEvent<
      CalledFallbackEvent.InputTuple,
      CalledFallbackEvent.OutputTuple,
      CalledFallbackEvent.OutputObject
    >;

    "CalledRestricted(address)": TypedContractEvent<
      CalledRestrictedEvent.InputTuple,
      CalledRestrictedEvent.OutputTuple,
      CalledRestrictedEvent.OutputObject
    >;
    CalledRestricted: TypedContractEvent<
      CalledRestrictedEvent.InputTuple,
      CalledRestrictedEvent.OutputTuple,
      CalledRestrictedEvent.OutputObject
    >;

    "CalledUnrestricted(address)": TypedContractEvent<
      CalledUnrestrictedEvent.InputTuple,
      CalledUnrestrictedEvent.OutputTuple,
      CalledUnrestrictedEvent.OutputObject
    >;
    CalledUnrestricted: TypedContractEvent<
      CalledUnrestrictedEvent.InputTuple,
      CalledUnrestrictedEvent.OutputTuple,
      CalledUnrestrictedEvent.OutputObject
    >;
  };
}
