/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ERC3156FlashBorrowerMockInterface extends Interface {
  getFunction(nameOrSignature: "onFlashLoan"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BalanceOf" | "TotalSupply"): EventFragment;

  encodeFunctionData(
    functionFragment: "onFlashLoan",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "onFlashLoan",
    data: BytesLike
  ): Result;
}

export namespace BalanceOfEvent {
  export type InputTuple = [
    token: AddressLike,
    account: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [token: string, account: string, value: bigint];
  export interface OutputObject {
    token: string;
    account: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalSupplyEvent {
  export type InputTuple = [token: AddressLike, value: BigNumberish];
  export type OutputTuple = [token: string, value: bigint];
  export interface OutputObject {
    token: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC3156FlashBorrowerMock extends BaseContract {
  connect(runner?: ContractRunner | null): ERC3156FlashBorrowerMock;
  waitForDeployment(): Promise<this>;

  interface: ERC3156FlashBorrowerMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  onFlashLoan: TypedContractMethod<
    [
      arg0: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      fee: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "onFlashLoan"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      fee: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "BalanceOf"
  ): TypedContractEvent<
    BalanceOfEvent.InputTuple,
    BalanceOfEvent.OutputTuple,
    BalanceOfEvent.OutputObject
  >;
  getEvent(
    key: "TotalSupply"
  ): TypedContractEvent<
    TotalSupplyEvent.InputTuple,
    TotalSupplyEvent.OutputTuple,
    TotalSupplyEvent.OutputObject
  >;

  filters: {
    "BalanceOf(address,address,uint256)": TypedContractEvent<
      BalanceOfEvent.InputTuple,
      BalanceOfEvent.OutputTuple,
      BalanceOfEvent.OutputObject
    >;
    BalanceOf: TypedContractEvent<
      BalanceOfEvent.InputTuple,
      BalanceOfEvent.OutputTuple,
      BalanceOfEvent.OutputObject
    >;

    "TotalSupply(address,uint256)": TypedContractEvent<
      TotalSupplyEvent.InputTuple,
      TotalSupplyEvent.OutputTuple,
      TotalSupplyEvent.OutputObject
    >;
    TotalSupply: TypedContractEvent<
      TotalSupplyEvent.InputTuple,
      TotalSupplyEvent.OutputTuple,
      TotalSupplyEvent.OutputObject
    >;
  };
}
