/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StorageSlotMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bytesMap"
      | "getAddress"
      | "getBoolean"
      | "getBytes"
      | "getBytes32"
      | "getBytesStorage"
      | "getString"
      | "getStringStorage"
      | "getUint256"
      | "setAddress"
      | "setBoolean"
      | "setBytes"
      | "setBytes32"
      | "setBytesStorage"
      | "setString"
      | "setStringStorage"
      | "setUint256"
      | "stringMap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bytesMap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoolean",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytesStorage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStringStorage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUint256",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBoolean",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytesStorage",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStringStorage",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint256",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringMap",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bytesMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBoolean", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBytesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStringStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUint256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBoolean", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBytesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStringStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUint256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stringMap", data: BytesLike): Result;
}

export interface StorageSlotMock extends BaseContract {
  connect(runner?: ContractRunner | null): StorageSlotMock;
  waitForDeployment(): Promise<this>;

  interface: StorageSlotMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bytesMap: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getAddress: TypedContractMethod<[slot: BytesLike], [string], "view">;

  getBoolean: TypedContractMethod<[slot: BytesLike], [boolean], "view">;

  getBytes: TypedContractMethod<[slot: BytesLike], [string], "view">;

  getBytes32: TypedContractMethod<[slot: BytesLike], [string], "view">;

  getBytesStorage: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getString: TypedContractMethod<[slot: BytesLike], [string], "view">;

  getStringStorage: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getUint256: TypedContractMethod<[slot: BytesLike], [bigint], "view">;

  setAddress: TypedContractMethod<
    [slot: BytesLike, value: AddressLike],
    [void],
    "nonpayable"
  >;

  setBoolean: TypedContractMethod<
    [slot: BytesLike, value: boolean],
    [void],
    "nonpayable"
  >;

  setBytes: TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;

  setBytes32: TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;

  setBytesStorage: TypedContractMethod<
    [key: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;

  setString: TypedContractMethod<
    [slot: BytesLike, value: string],
    [void],
    "nonpayable"
  >;

  setStringStorage: TypedContractMethod<
    [key: BigNumberish, value: string],
    [void],
    "nonpayable"
  >;

  setUint256: TypedContractMethod<
    [slot: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  stringMap: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bytesMap"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[slot: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBoolean"
  ): TypedContractMethod<[slot: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBytes"
  ): TypedContractMethod<[slot: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBytes32"
  ): TypedContractMethod<[slot: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBytesStorage"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getString"
  ): TypedContractMethod<[slot: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStringStorage"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getUint256"
  ): TypedContractMethod<[slot: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [slot: BytesLike, value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBoolean"
  ): TypedContractMethod<
    [slot: BytesLike, value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes"
  ): TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes32"
  ): TypedContractMethod<
    [slot: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytesStorage"
  ): TypedContractMethod<
    [key: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setString"
  ): TypedContractMethod<
    [slot: BytesLike, value: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStringStorage"
  ): TypedContractMethod<
    [key: BigNumberish, value: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUint256"
  ): TypedContractMethod<
    [slot: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stringMap"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;

  filters: {};
}
