/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TimelockReentrantInterface extends Interface {
  getFunction(
    nameOrSignature: "disableReentrancy" | "enableRentrancy" | "reenter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disableReentrancy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableRentrancy",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "reenter", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "disableReentrancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableRentrancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reenter", data: BytesLike): Result;
}

export interface TimelockReentrant extends BaseContract {
  connect(runner?: ContractRunner | null): TimelockReentrant;
  waitForDeployment(): Promise<this>;

  interface: TimelockReentrantInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  disableReentrancy: TypedContractMethod<[], [void], "nonpayable">;

  enableRentrancy: TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  reenter: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "disableReentrancy"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableRentrancy"
  ): TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reenter"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
