/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Implementation2,
  Implementation2Interface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/RegressionImplementation.sol/Implementation2";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610386806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063209652551461004657806355241077146100645780638129fc1c14610080575b600080fd5b61004e61008a565b60405161005b9190610263565b60405180910390f35b61007e600480360381019061007991906102af565b610093565b005b61008861009d565b005b60008054905090565b8060008190555050565b60006100a7610222565b905060008160000160089054906101000a900460ff1615905060008260000160009054906101000a900467ffffffffffffffff1690506000808267ffffffffffffffff161480156100f55750825b9050600060018367ffffffffffffffff1614801561012a575060003073ffffffffffffffffffffffffffffffffffffffff163b145b905081158015610138575080155b1561016f576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60018560000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555083156101bf5760018560000160086101000a81548160ff0219169083151502179055505b831561021b5760008560000160086101000a81548160ff0219169083151502179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d260016040516102129190610335565b60405180910390a15b5050505050565b60007ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00905090565b6000819050919050565b61025d8161024a565b82525050565b60006020820190506102786000830184610254565b92915050565b600080fd5b61028c8161024a565b811461029757600080fd5b50565b6000813590506102a981610283565b92915050565b6000602082840312156102c5576102c461027e565b5b60006102d38482850161029a565b91505092915050565b6000819050919050565b600067ffffffffffffffff82169050919050565b6000819050919050565b600061031f61031a610315846102dc565b6102fa565b6102e6565b9050919050565b61032f81610304565b82525050565b600060208201905061034a6000830184610326565b9291505056fea264697066735822122097b4876424f4d20e4d75d6bef13914be802c6724c1a4b3c6cbca80248ce1694864736f6c63430008140033";

type Implementation2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation2__factory extends ContractFactory {
  constructor(...args: Implementation2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Implementation2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Implementation2__factory {
    return super.connect(runner) as Implementation2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation2Interface {
    return new Interface(_abi) as Implementation2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Implementation2 {
    return new Contract(address, _abi, runner) as unknown as Implementation2;
  }
}
