/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Implementation4,
  Implementation4Interface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/RegressionImplementation.sol/Implementation4";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061038f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100455760003560e01c8063209652551461004f578063552410771461006d5780638129fc1c1461008957610046565b5b60016000819055005b610057610093565b604051610064919061026c565b60405180910390f35b610087600480360381019061008291906102b8565b61009c565b005b6100916100a6565b005b60008054905090565b8060008190555050565b60006100b061022b565b905060008160000160089054906101000a900460ff1615905060008260000160009054906101000a900467ffffffffffffffff1690506000808267ffffffffffffffff161480156100fe5750825b9050600060018367ffffffffffffffff16148015610133575060003073ffffffffffffffffffffffffffffffffffffffff163b145b905081158015610141575080155b15610178576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60018560000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555083156101c85760018560000160086101000a81548160ff0219169083151502179055505b83156102245760008560000160086101000a81548160ff0219169083151502179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2600160405161021b919061033e565b60405180910390a15b5050505050565b60007ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00905090565b6000819050919050565b61026681610253565b82525050565b6000602082019050610281600083018461025d565b92915050565b600080fd5b61029581610253565b81146102a057600080fd5b50565b6000813590506102b28161028c565b92915050565b6000602082840312156102ce576102cd610287565b5b60006102dc848285016102a3565b91505092915050565b6000819050919050565b600067ffffffffffffffff82169050919050565b6000819050919050565b600061032861032361031e846102e5565b610303565b6102ef565b9050919050565b6103388161030d565b82525050565b6000602082019050610353600083018461032f565b9291505056fea26469706673582212205d3b4b52b06b347eda2cfae6459c0485411ece42e38bf83001da2b4ec753f32564736f6c63430008140033";

type Implementation4ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation4ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation4__factory extends ContractFactory {
  constructor(...args: Implementation4ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Implementation4 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Implementation4__factory {
    return super.connect(runner) as Implementation4__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation4Interface {
    return new Interface(_abi) as Implementation4Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Implementation4 {
    return new Contract(address, _abi, runner) as unknown as Implementation4;
  }
}
