/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AuthoritiyObserveIsConsumingInterface extends Interface {
  getFunction(
    nameOrSignature: "canCall" | "consumeScheduledOp"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ConsumeScheduledOpCalled"): EventFragment;

  encodeFunctionData(
    functionFragment: "canCall",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeScheduledOp",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "canCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "consumeScheduledOp",
    data: BytesLike
  ): Result;
}

export namespace ConsumeScheduledOpCalledEvent {
  export type InputTuple = [
    caller: AddressLike,
    data: BytesLike,
    isConsuming: BytesLike
  ];
  export type OutputTuple = [caller: string, data: string, isConsuming: string];
  export interface OutputObject {
    caller: string;
    data: string;
    isConsuming: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuthoritiyObserveIsConsuming extends BaseContract {
  connect(runner?: ContractRunner | null): AuthoritiyObserveIsConsuming;
  waitForDeployment(): Promise<this>;

  interface: AuthoritiyObserveIsConsumingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canCall: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;

  consumeScheduledOp: TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canCall"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "consumeScheduledOp"
  ): TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsumeScheduledOpCalled"
  ): TypedContractEvent<
    ConsumeScheduledOpCalledEvent.InputTuple,
    ConsumeScheduledOpCalledEvent.OutputTuple,
    ConsumeScheduledOpCalledEvent.OutputObject
  >;

  filters: {
    "ConsumeScheduledOpCalled(address,bytes,bytes4)": TypedContractEvent<
      ConsumeScheduledOpCalledEvent.InputTuple,
      ConsumeScheduledOpCalledEvent.OutputTuple,
      ConsumeScheduledOpCalledEvent.OutputObject
    >;
    ConsumeScheduledOpCalled: TypedContractEvent<
      ConsumeScheduledOpCalledEvent.InputTuple,
      ConsumeScheduledOpCalledEvent.OutputTuple,
      ConsumeScheduledOpCalledEvent.OutputObject
    >;
  };
}
