/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AuthorityDelayMockInterface extends Interface {
  getFunction(
    nameOrSignature: "_setDelay" | "_setImmediate" | "canCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_setDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_setImmediate",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "canCall",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "_setDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_setImmediate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canCall", data: BytesLike): Result;
}

export interface AuthorityDelayMock extends BaseContract {
  connect(runner?: ContractRunner | null): AuthorityDelayMock;
  waitForDeployment(): Promise<this>;

  interface: AuthorityDelayMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _setDelay: TypedContractMethod<[delay: BigNumberish], [void], "nonpayable">;

  _setImmediate: TypedContractMethod<
    [immediate: boolean],
    [void],
    "nonpayable"
  >;

  canCall: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_setDelay"
  ): TypedContractMethod<[delay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "_setImmediate"
  ): TypedContractMethod<[immediate: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canCall"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BytesLike],
    [[boolean, bigint] & { immediate: boolean; delay: bigint }],
    "view"
  >;

  filters: {};
}
