/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuthoritiyObserveIsConsuming } from "./AuthoritiyObserveIsConsuming";
export type { AuthorityDelayMock } from "./AuthorityDelayMock";
export type { AuthorityNoDelayMock } from "./AuthorityNoDelayMock";
export type { AuthorityNoResponse } from "./AuthorityNoResponse";
export type { NotAuthorityMock } from "./NotAuthorityMock";
