/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1271MaliciousMock } from "./ERC1271MaliciousMock";
export type { ERC1271WalletMock } from "./ERC1271WalletMock";
