/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  SampleHuman,
  SampleHumanInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/MultipleInheritanceInitializableMocks.sol/SampleHuman";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061039f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80634a6c9db61461003b5780638129fc1c14610059575b600080fd5b610043610063565b60405161005091906102da565b60405180910390f35b610061610074565b005b60008054906101000a900460ff1681565b600061007e610201565b905060008160000160089054906101000a900460ff1615905060008260000160009054906101000a900467ffffffffffffffff1690506000808267ffffffffffffffff161480156100cc5750825b9050600060018367ffffffffffffffff16148015610101575060003073ffffffffffffffffffffffffffffffffffffffff163b145b90508115801561010f575080155b15610146576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60018560000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555083156101965760018560000160086101000a81548160ff0219169083151502179055505b61019e610229565b83156101fa5760008560000160086101000a81548160ff0219169083151502179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d260016040516101f1919061034e565b60405180910390a15b5050505050565b60007ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00905090565b61023161023b565b61023961027b565b565b61024361029f565b610279576040517fd7e6bcf800000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b565b61028361023b565b60016000806101000a81548160ff021916908315150217905550565b60006102a9610201565b60000160089054906101000a900460ff16905090565b60008115159050919050565b6102d4816102bf565b82525050565b60006020820190506102ef60008301846102cb565b92915050565b6000819050919050565b600067ffffffffffffffff82169050919050565b6000819050919050565b600061033861033361032e846102f5565b610313565b6102ff565b9050919050565b6103488161031d565b82525050565b6000602082019050610363600083018461033f565b9291505056fea2646970667358221220bc633dcf7ebbb72df754b98111d1c91b696ee8d603cfe5c62ec3ec24b789c08b64736f6c63430008140033";

type SampleHumanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SampleHumanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SampleHuman__factory extends ContractFactory {
  constructor(...args: SampleHumanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SampleHuman & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SampleHuman__factory {
    return super.connect(runner) as SampleHuman__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SampleHumanInterface {
    return new Interface(_abi) as SampleHumanInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SampleHuman {
    return new Contract(address, _abi, runner) as unknown as SampleHuman;
  }
}
