/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SampleChildInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "child"
      | "father"
      | "gramps"
      | "initialize(uint256,string,uint256,uint256)"
      | "initialize()"
      | "initialize(string,uint256)"
      | "initialize(string)"
      | "initialize(uint256)"
      | "isHuman"
      | "mother"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;

  encodeFunctionData(functionFragment: "child", values?: undefined): string;
  encodeFunctionData(functionFragment: "father", values?: undefined): string;
  encodeFunctionData(functionFragment: "gramps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize(uint256,string,uint256,uint256)",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(string,uint256)",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isHuman", values?: undefined): string;
  encodeFunctionData(functionFragment: "mother", values?: undefined): string;

  decodeFunctionResult(functionFragment: "child", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "father", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gramps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialize(uint256,string,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHuman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mother", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SampleChild extends BaseContract {
  connect(runner?: ContractRunner | null): SampleChild;
  waitForDeployment(): Promise<this>;

  interface: SampleChildInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  child: TypedContractMethod<[], [bigint], "view">;

  father: TypedContractMethod<[], [bigint], "view">;

  gramps: TypedContractMethod<[], [string], "view">;

  "initialize(uint256,string,uint256,uint256)": TypedContractMethod<
    [
      _mother: BigNumberish,
      _gramps: string,
      _father: BigNumberish,
      _child: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "initialize()": TypedContractMethod<[], [void], "nonpayable">;

  "initialize(string,uint256)": TypedContractMethod<
    [_gramps: string, _father: BigNumberish],
    [void],
    "nonpayable"
  >;

  "initialize(string)": TypedContractMethod<
    [value: string],
    [void],
    "nonpayable"
  >;

  "initialize(uint256)": TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  isHuman: TypedContractMethod<[], [boolean], "view">;

  mother: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "child"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "father"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gramps"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize(uint256,string,uint256,uint256)"
  ): TypedContractMethod<
    [
      _mother: BigNumberish,
      _gramps: string,
      _father: BigNumberish,
      _child: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize(string,uint256)"
  ): TypedContractMethod<
    [_gramps: string, _father: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize(string)"
  ): TypedContractMethod<[value: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize(uint256)"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isHuman"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mother"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
  };
}
