/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DisableOld,
  DisableOldInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/InitializableMock.sol/DisableOld";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50600061002161019f60201b60201c565b905060008160000160089054906101000a900460ff1615905060008260000160009054906101000a900467ffffffffffffffff1690506000808267ffffffffffffffff1614801561006f5750825b9050600060018367ffffffffffffffff161480156100a4575060003073ffffffffffffffffffffffffffffffffffffffff163b145b9050811580156100b2575080155b156100e9576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60018560000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555083156101395760018560000160086101000a81548160ff0219169083151502179055505b83156101955760008560000160086101000a81548160ff0219169083151502179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2600160405161018c9190610220565b60405180910390a15b505050505061023b565b60007ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00905090565b6000819050919050565b600067ffffffffffffffff82169050919050565b6000819050919050565b600061020a610205610200846101c7565b6101e5565b6101d1565b9050919050565b61021a816101ef565b82525050565b60006020820190506102356000830184610211565b92915050565b603f806102496000396000f3fe6080604052600080fdfea2646970667358221220b0c044885cf0da5de2d09f95b6f6560751279c73da4a36f9c745faef4fa40a5764736f6c63430008140033";

type DisableOldConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DisableOldConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DisableOld__factory extends ContractFactory {
  constructor(...args: DisableOldConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DisableOld & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DisableOld__factory {
    return super.connect(runner) as DisableOld__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DisableOldInterface {
    return new Interface(_abi) as DisableOldInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DisableOld {
    return new Contract(address, _abi, runner) as unknown as DisableOld;
  }
}
