/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DisableBad2,
  DisableBad2Interface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/InitializableMock.sol/DisableBad2";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060006100216101ad60201b60201c565b905060008160000160089054906101000a900460ff1615905060008260000160009054906101000a900467ffffffffffffffff1690506000808267ffffffffffffffff1614801561006f5750825b9050600060018367ffffffffffffffff161480156100a4575060003073ffffffffffffffffffffffffffffffffffffffff163b145b9050811580156100b2575080155b156100e9576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60018560000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555083156101395760018560000160086101000a81548160ff0219169083151502179055505b6101476101d560201b60201c565b83156101a35760008560000160086101000a81548160ff0219169083151502179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2600160405161019a9190610332565b60405180910390a15b5050505050610377565b60007ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00905090565b60006101e56101ad60201b60201c565b90508060000160089054906101000a900460ff1615610230576040517ff92ee8a900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b67ffffffffffffffff80168160000160009054906101000a900467ffffffffffffffff1667ffffffffffffffff16146102d65767ffffffffffffffff8160000160006101000a81548167ffffffffffffffff021916908367ffffffffffffffff1602179055507fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d267ffffffffffffffff6040516102cd919061035c565b60405180910390a15b50565b6000819050919050565b600067ffffffffffffffff82169050919050565b6000819050919050565b600061031c610317610312846102d9565b6102f7565b6102e3565b9050919050565b61032c81610301565b82525050565b60006020820190506103476000830184610323565b92915050565b610356816102e3565b82525050565b6000602082019050610371600083018461034d565b92915050565b603f806103856000396000f3fe6080604052600080fdfea264697066735822122092f94479f23516c42fadfed7e52c03434e77243d25d57344b88522bc0931d68564736f6c63430008140033";

type DisableBad2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DisableBad2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DisableBad2__factory extends ContractFactory {
  constructor(...args: DisableBad2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DisableBad2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DisableBad2__factory {
    return super.connect(runner) as DisableBad2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DisableBad2Interface {
    return new Interface(_abi) as DisableBad2Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): DisableBad2 {
    return new Contract(address, _abi, runner) as unknown as DisableBad2;
  }
}
