/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20VotesTimestampMock__factory } from "./ERC20VotesTimestampMock__factory";
export { ERC721VotesTimestampMock__factory } from "./ERC721VotesTimestampMock__factory";
