/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ERC20ExcessDecimalsMock,
  ERC20ExcessDecimalsMockInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/token/ERC20ExcessDecimalsMock";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060d58061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063313ce56714602d575b600080fd5b60336047565b604051603e91906086565b60405180910390f35b60007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff905090565b6000819050919050565b608081606f565b82525050565b6000602082019050609960008301846079565b9291505056fea2646970667358221220cfa33b6706a240fa8099cf69000d116bc2213224e802a9185ae59d9d5af1b39864736f6c63430008140033";

type ERC20ExcessDecimalsMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC20ExcessDecimalsMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC20ExcessDecimalsMock__factory extends ContractFactory {
  constructor(...args: ERC20ExcessDecimalsMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERC20ExcessDecimalsMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ERC20ExcessDecimalsMock__factory {
    return super.connect(runner) as ERC20ExcessDecimalsMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC20ExcessDecimalsMockInterface {
    return new Interface(_abi) as ERC20ExcessDecimalsMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC20ExcessDecimalsMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ERC20ExcessDecimalsMock;
  }
}
