/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChildConstructorInitializableMock } from "./ChildConstructorInitializableMock";
export type { ConstructorInitializableMock } from "./ConstructorInitializableMock";
export type { DisableBad1 } from "./DisableBad1";
export type { DisableBad2 } from "./DisableBad2";
export type { DisableNew } from "./DisableNew";
export type { DisableOk } from "./DisableOk";
export type { DisableOld } from "./DisableOld";
export type { InitializableMock } from "./InitializableMock";
export type { ReinitializerMock } from "./ReinitializerMock";
