/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface InitializableMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fail"
      | "initialize"
      | "initializeOnlyInitializing"
      | "initializeWithX"
      | "initializerNested"
      | "initializerRan"
      | "isInitializing"
      | "nonInitializable"
      | "onlyInitializingNested"
      | "onlyInitializingRan"
      | "x"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;

  encodeFunctionData(functionFragment: "fail", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeOnlyInitializing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWithX",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializerNested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializerRan",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitializing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonInitializable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onlyInitializingNested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onlyInitializingRan",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "x", values?: undefined): string;

  decodeFunctionResult(functionFragment: "fail", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeOnlyInitializing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializerNested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializerRan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitializing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonInitializable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyInitializingNested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyInitializingRan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "x", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InitializableMock extends BaseContract {
  connect(runner?: ContractRunner | null): InitializableMock;
  waitForDeployment(): Promise<this>;

  interface: InitializableMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fail: TypedContractMethod<[], [void], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initializeOnlyInitializing: TypedContractMethod<[], [void], "nonpayable">;

  initializeWithX: TypedContractMethod<[_x: BigNumberish], [void], "payable">;

  initializerNested: TypedContractMethod<[], [void], "nonpayable">;

  initializerRan: TypedContractMethod<[], [boolean], "view">;

  isInitializing: TypedContractMethod<[], [boolean], "view">;

  nonInitializable: TypedContractMethod<[_x: BigNumberish], [void], "payable">;

  onlyInitializingNested: TypedContractMethod<[], [void], "nonpayable">;

  onlyInitializingRan: TypedContractMethod<[], [boolean], "view">;

  x: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "fail"): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeOnlyInitializing"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeWithX"
  ): TypedContractMethod<[_x: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "initializerNested"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializerRan"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isInitializing"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonInitializable"
  ): TypedContractMethod<[_x: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "onlyInitializingNested"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onlyInitializingRan"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(nameOrSignature: "x"): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
  };
}
