/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AuthorityNoDelayMock,
  AuthorityNoDelayMockInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/AuthorityMock.sol/AuthorityNoDelayMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "immediate",
        type: "bool",
      },
    ],
    name: "_setImmediate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    name: "canCall",
    outputs: [
      {
        internalType: "bool",
        name: "immediate",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610290806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633e5047b21461003b578063b700961314610057575b600080fd5b610055600480360381019061005091906100fa565b610087565b005b610071600480360381019061006c91906101dd565b6100a3565b60405161007e919061023f565b60405180910390f35b806000806101000a81548160ff02191690831515021790555050565b60008060009054906101000a900460ff1690509392505050565b600080fd5b60008115159050919050565b6100d7816100c2565b81146100e257600080fd5b50565b6000813590506100f4816100ce565b92915050565b6000602082840312156101105761010f6100bd565b5b600061011e848285016100e5565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061015282610127565b9050919050565b61016281610147565b811461016d57600080fd5b50565b60008135905061017f81610159565b92915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6101ba81610185565b81146101c557600080fd5b50565b6000813590506101d7816101b1565b92915050565b6000806000606084860312156101f6576101f56100bd565b5b600061020486828701610170565b935050602061021586828701610170565b9250506040610226868287016101c8565b9150509250925092565b610239816100c2565b82525050565b60006020820190506102546000830184610230565b9291505056fea2646970667358221220355824fd0d424c3eae8268d1de836d575144b5515d3e9e7e097e05b4d095273164736f6c63430008140033";

type AuthorityNoDelayMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuthorityNoDelayMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuthorityNoDelayMock__factory extends ContractFactory {
  constructor(...args: AuthorityNoDelayMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuthorityNoDelayMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AuthorityNoDelayMock__factory {
    return super.connect(runner) as AuthorityNoDelayMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuthorityNoDelayMockInterface {
    return new Interface(_abi) as AuthorityNoDelayMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuthorityNoDelayMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AuthorityNoDelayMock;
  }
}
