/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AuthorityNoResponse,
  AuthorityNoResponseInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/AuthorityMock.sol/AuthorityNoResponse";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    name: "canCall",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610195806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b700961314610030575b600080fd5b61004a6004803603810190610045919061010c565b61004c565b005b505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061008182610056565b9050919050565b61009181610076565b811461009c57600080fd5b50565b6000813590506100ae81610088565b92915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6100e9816100b4565b81146100f457600080fd5b50565b600081359050610106816100e0565b92915050565b60008060006060848603121561012557610124610051565b5b60006101338682870161009f565b93505060206101448682870161009f565b9250506040610155868287016100f7565b915050925092509256fea264697066735822122010247536813f2f6b48a7f79821ca075686b521668500506dad81d94e65f429bf64736f6c63430008140033";

type AuthorityNoResponseConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuthorityNoResponseConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuthorityNoResponse__factory extends ContractFactory {
  constructor(...args: AuthorityNoResponseConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuthorityNoResponse & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AuthorityNoResponse__factory {
    return super.connect(runner) as AuthorityNoResponse__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuthorityNoResponseInterface {
    return new Interface(_abi) as AuthorityNoResponseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuthorityNoResponse {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AuthorityNoResponse;
  }
}
