/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotesMock } from "./VotesMock";
export type { VotesTimestampMock } from "./VotesTimestampMock";
