/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc4646FeesMockSol from "./ERC4646FeesMock.sol";
export type { erc4646FeesMockSol };
import type * as erc721ConsecutiveMockSol from "./ERC721ConsecutiveMock.sol";
export type { erc721ConsecutiveMockSol };
import type * as votesTimestampSol from "./VotesTimestamp.sol";
export type { votesTimestampSol };
export type { ERC1155ReceiverMock } from "./ERC1155ReceiverMock";
export type { ERC20ApprovalMock } from "./ERC20ApprovalMock";
export type { ERC20DecimalsMock } from "./ERC20DecimalsMock";
export type { ERC20ExcessDecimalsMock } from "./ERC20ExcessDecimalsMock";
export type { ERC20FlashMintMock } from "./ERC20FlashMintMock";
export type { ERC20ForceApproveMock } from "./ERC20ForceApproveMock";
export type { ERC20Mock } from "./ERC20Mock";
export type { ERC20MulticallMock } from "./ERC20MulticallMock";
export type { ERC20NoReturnMock } from "./ERC20NoReturnMock";
export type { ERC20Reentrant } from "./ERC20Reentrant";
export type { ERC20ReturnFalseMock } from "./ERC20ReturnFalseMock";
export type { ERC20VotesLegacyMock } from "./ERC20VotesLegacyMock";
export type { ERC4626LimitsMock } from "./ERC4626LimitsMock";
export type { ERC4626Mock } from "./ERC4626Mock";
export type { ERC4626OffsetMock } from "./ERC4626OffsetMock";
export type { ERC721ConsecutiveEnumerableMock } from "./ERC721ConsecutiveEnumerableMock";
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { ERC721URIStorageMock } from "./ERC721URIStorageMock";
