/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorVoteMockSol from "./GovernorVoteMock.sol";
export { GovernorMock__factory } from "./GovernorMock__factory";
export { GovernorPreventLateQuorumMock__factory } from "./GovernorPreventLateQuorumMock__factory";
export { GovernorStorageMock__factory } from "./GovernorStorageMock__factory";
export { GovernorTimelockAccessMock__factory } from "./GovernorTimelockAccessMock__factory";
export { GovernorTimelockCompoundMock__factory } from "./GovernorTimelockCompoundMock__factory";
export { GovernorTimelockControlMock__factory } from "./GovernorTimelockControlMock__factory";
export { GovernorWithParamsMock__factory } from "./GovernorWithParamsMock__factory";
