/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyGovernor } from "./MyGovernor";
export type { MyToken } from "./MyToken";
export type { MyTokenTimestampBased } from "./MyTokenTimestampBased";
export type { MyTokenWrapped } from "./MyTokenWrapped";
