/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControl from "./access-control";
export type { accessControl };
import type * as governance from "./governance";
export type { governance };
export type { ERC20WithAutoMinerReward } from "./ERC20WithAutoMinerReward";
export type { ERC4626Fees } from "./ERC4626Fees";
