/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControlErc20MintOnlyRoleSol from "./AccessControlERC20MintOnlyRole.sol";
export type { accessControlErc20MintOnlyRoleSol };
import type * as accessManagedErc20MintBaseSol from "./AccessManagedERC20MintBase.sol";
export type { accessManagedErc20MintBaseSol };
import type * as myContractOwnableSol from "./MyContractOwnable.sol";
export type { myContractOwnableSol };
export type { AccessControlERC20MintBase } from "./AccessControlERC20MintBase";
export type { AccessControlERC20MintMissing } from "./AccessControlERC20MintMissing";
