/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorVoteMockSol from "./GovernorVoteMock.sol";
export type { governorVoteMockSol };
export type { GovernorMock } from "./GovernorMock";
export type { GovernorPreventLateQuorumMock } from "./GovernorPreventLateQuorumMock";
export type { GovernorStorageMock } from "./GovernorStorageMock";
export type { GovernorTimelockAccessMock } from "./GovernorTimelockAccessMock";
export type { GovernorTimelockCompoundMock } from "./GovernorTimelockCompoundMock";
export type { GovernorTimelockControlMock } from "./GovernorTimelockControlMock";
export type { GovernorWithParamsMock } from "./GovernorWithParamsMock";
