/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  NonUpgradeableMock,
  NonUpgradeableMockInterface,
} from "../../../../../openzeppelin-contracts-5.0.0/mocks/proxy/UUPSUpgradeableMock.sol/NonUpgradeableMock";

const _abi = [
  {
    inputs: [],
    name: "current",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610164806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639fa6a6e31461003b578063d09de08a14610059575b600080fd5b610043610063565b604051610050919061009c565b60405180910390f35b61006161006c565b005b60008054905090565b600080815461007a906100e6565b91905081905550565b6000819050919050565b61009681610083565b82525050565b60006020820190506100b1600083018461008d565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006100f182610083565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8203610123576101226100b7565b5b60018201905091905056fea2646970667358221220869d8db86f7bdf799093bf554d061dea043d4769437f6bf0ff8ac46d4baf36a464736f6c63430008140033";

type NonUpgradeableMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NonUpgradeableMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NonUpgradeableMock__factory extends ContractFactory {
  constructor(...args: NonUpgradeableMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NonUpgradeableMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NonUpgradeableMock__factory {
    return super.connect(runner) as NonUpgradeableMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NonUpgradeableMockInterface {
    return new Interface(_abi) as NonUpgradeableMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NonUpgradeableMock {
    return new Contract(address, _abi, runner) as unknown as NonUpgradeableMock;
  }
}
