/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ConsecutiveMock } from "./ERC721ConsecutiveMock";
export type { ERC721ConsecutiveNoConstructorMintMock } from "./ERC721ConsecutiveNoConstructorMintMock";
