/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyGovernor__factory } from "./MyGovernor__factory";
export { MyToken__factory } from "./MyToken__factory";
export { MyTokenTimestampBased__factory } from "./MyTokenTimestampBased__factory";
export { MyTokenWrapped__factory } from "./MyTokenWrapped__factory";
