/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ClashingImplementationInterface extends Interface {
  getFunction(
    nameOrSignature: "delegatedFunction" | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ClashingImplementationCall"): EventFragment;

  encodeFunctionData(
    functionFragment: "delegatedFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "delegatedFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ClashingImplementationCallEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClashingImplementation extends BaseContract {
  connect(runner?: ContractRunner | null): ClashingImplementation;
  waitForDeployment(): Promise<this>;

  interface: ClashingImplementationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delegatedFunction: TypedContractMethod<[], [boolean], "view">;

  upgradeToAndCall: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delegatedFunction"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ClashingImplementationCall"
  ): TypedContractEvent<
    ClashingImplementationCallEvent.InputTuple,
    ClashingImplementationCallEvent.OutputTuple,
    ClashingImplementationCallEvent.OutputObject
  >;

  filters: {
    "ClashingImplementationCall()": TypedContractEvent<
      ClashingImplementationCallEvent.InputTuple,
      ClashingImplementationCallEvent.OutputTuple,
      ClashingImplementationCallEvent.OutputObject
    >;
    ClashingImplementationCall: TypedContractEvent<
      ClashingImplementationCallEvent.InputTuple,
      ClashingImplementationCallEvent.OutputTuple,
      ClashingImplementationCallEvent.OutputObject
    >;
  };
}
