/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as badBeaconSol from "./BadBeacon.sol";
export type { badBeaconSol };
import type * as uupsUpgradeableMockSol from "./UUPSUpgradeableMock.sol";
export type { uupsUpgradeableMockSol };
export type { ClashingImplementation } from "./ClashingImplementation";
