/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ERC165MissingData,
  ERC165MissingDataInterface,
} from "../../../../openzeppelin-contracts-5.0.0/mocks/ERC165/ERC165MissingData";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060fe8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806301ffc9a714602d575b600080fd5b60436004803603810190603f919060a0565b6045565b005b50565b600080fd5b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b608081604d565b8114608a57600080fd5b50565b600081359050609a816079565b92915050565b60006020828403121560b35760b26048565b5b600060bf84828501608d565b9150509291505056fea2646970667358221220a479c9a89f11bb468994ed7d29f9f20b856f8c4d6bf83feaefbbf750f0a94dc964736f6c63430008140033";

type ERC165MissingDataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC165MissingDataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC165MissingData__factory extends ContractFactory {
  constructor(...args: ERC165MissingDataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERC165MissingData & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC165MissingData__factory {
    return super.connect(runner) as ERC165MissingData__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC165MissingDataInterface {
    return new Interface(_abi) as ERC165MissingDataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC165MissingData {
    return new Contract(address, _abi, runner) as unknown as ERC165MissingData;
  }
}
